<?php
/* 
Written by: Viviannie De La Fuente
Tested by: Viviannie De La Fuente
Debugged by: Viviannie De La Fuente 
*/
session_start();
require_once "config.php";

// Need to get what was passed in
$q = $_GET['q'];

    $sql = "SELECT id FROM general_user_information WHERE qrCodeId=?"; // SQL with parameters
    $stmt = $mysqli->prepare($sql);
    $stmt->bind_param("s", $q);
    $stmt->execute();
    $result = $stmt->get_result();
  
    function saveLog($logDate, $businessId, $id, $con) {
        // Saving scan details into the details
        // NEED: businessId, time, date, id (of the user who got scanned)
        // attempt insert query execution
    $sql = "INSERT INTO scan_logs(    
        logTime,     
        logDate,
        businessId,
        id
    )
    VALUES(    
    now(),    
    '$logDate',
    '$businessId',
    '$id'    
    )";
    if(mysqli_query($con, $sql)){
       // echo nl2br("Records added successfully to business_information table.");
       
    } else{
      // echo nl2br("ERROR: Failed to execute $sql. " . mysqli_error($con));
    }
    // close connection
    mysqli_close($con);

      }
      
    // Check to see if the qr code is one generated by the system
    $row = $result->fetch_assoc();
    if ( $row) {
        $id_result =  $row['id'];
        $currentDate = date("Y-m-d");
        // $currentDate = new DateTime("now", new DateTimeZone('Canada/Atlantic') );
        // $currentDate= $currentDate->format('Y-m-d');
        // Need to get the current user's ID from Session array
        $bId = $_SESSION["id"];
      
        saveLog($currentDate, $bId, $id_result, $mysqli);
        echo "Valid";
    }
    else{
        echo "Invalid";
    }
    
   
    
?>
